spring.application.name=backend
# spring.profiles.active=local

server.port=${PORT:8080}

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Security Logging
logging.level.org.springframework.security=DEBUG

# JWT
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-minutes=1440

# Auth Cookie
app.cookie.secure=${APP_COOKIE_SECURE:true}
app.cookie.same-site=${APP_COOKIE_SAME_SITE:None}
